spring: 
  profiles:
    active:
    - dev
    
---
spring: 
  profiles: dev
  application:
    name: microservicecloud-config-lyh-dev
 
---
spring: 
  profiles: test
  application:
    name: microservicecloud-config-lyh-test
    
# 请保存为UTF-8格式    